### ISSUE TITLE
🛠️  Refactor: Page Size

### ISSUE THREAD

**Issue by jcserv** [jcserv/ulinks#65]
### Motivation 🏁

Handling page size for different display sizes is a bit tricky - the frontend is good in the sense that it'll neatly organize the entries into grids responsively, but the rows are uneven if your width has rows of 3 entries (since we return 8 currently)

### Describe your refactoring solution 🛠️

After talking it through with @CometWhoosh, there's two solutions:

1. determine dimension size and request a certain page size to backend (FE+BE soln)
2. display as many full rows as the screen size allows, and then hide remaining entries in the next page (FE soln)

CC @AipioxTechson for your thoughts on this too!

**Comment by AipioxTechson** [comment]
I like the first solution, it provides more flexibility to the frontend and backend, though one caveat is that if you request a different page size each time, you may receive duplicate entries.

**Comment by AipioxTechson** [comment]
As for the 2nd solution, this would require the frontend to keep track of the hidden GC's with an edge case on it being the last page.

**Comment by Yousef-Bulbulia** [comment]
I agree with Aipiox, I prefer the first solution.
