### ISSUE TITLE
🚀 Feature Request: Dynamic Contributors

### ISSUE THREAD

**Issue by jcserv** [jcserv/ulinks#70]
### Overview 👁️‍🗨️

As more contributors come on board, it's cumbersome to update the footer each time.
We should use the Github API to get a list of all contributors and render their github profile, a popover to display their name, and when clicked should link to their github profile.

1. Use Axios to send a GET request to the Github API for this repo
2. Use response to render a row of contributors

### Additional details ℹ️

Some useful links:

https://docs.github.com/en/rest/reference/repos#list-repository-contributors

https://chakra-ui.com/docs/media-and-icons/avatar

https://github.com/white-van/discussion-board/commit/0a63123b12eeb0ab4a5f4f639469b1e2d1e3977d

https://github.com/utm-cssc/website/blob/master/components/global/Contributors.vue

**Comment by jordanburr22** [comment]
I can give this one a try

**Comment by jcserv** [comment]
Hey @jordanburr22, thanks for helping out! Feel free to reach out for any help. You can also dm me on Discord: jerry#0004

**Comment by jordanburr22** [comment]
@jcserv what's your Discord username?

**Comment by jcserv** [comment]
it's `jerry#0004`

**Comment by jordanburr22** [comment]
It's not working for some reason 🙃. Mine is jordanburr#4753
