### ISSUE TITLE
🚀 Feature Request: Relevance for Courses based on Semester

### ISSUE THREAD

**Issue by jcserv** [jcserv/ulinks#95]
### Overview 👁️‍🗨️

Currently we're displaying group chats based on two metrics: views and clicks.
However, for the upcoming term's course group chats we'll want to change how we display results so that "fresh" group chats will still have be displayed prominently so that students can easily find them.

### Proposed Change
Change the search resolver to conditionally sort on recent date

**Comment by Yousef-Bulbulia** [comment]
For course chats, we should also display the year and term that the course is taking place in on the chat card, so that users who are browsing for chats know which ones are for the current semester and which ones are outdated.
